apiVersion: v1
kind: Service
metadata:
  name: flight-price-pred-service
spec:
  type: NodePort
  selector:
    app: flight-price-pred
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30008
